// priority: 0

console.info('Hello, World! (You will see this line every time server resources reload)')

ServerEvents.recipes(event => {
	// Change recipes here
})

ServerEvents.tags('item', event => {
	// Get the #forge:cobblestone tag collection and add Diamond Ore to it
	// event.get('forge:cobblestone').add('minecraft:diamond_ore')

	// Get the #forge:cobblestone tag collection and remove Mossy Cobblestone from it
	// event.get('forge:cobblestone').remove('minecraft:mossy_cobblestone')
})

ServerEvents.recipes(event => {

// ====================================================================================================================
// =============================================== Remove Craft Recipes ===============================================
// ====================================================================================================================

	// Remove Cataclysm Ender Eyes craft recipes
	event.remove({output: 'cataclysm:mech_eye'})
	event.remove({output: 'cataclysm:flame_eye'})
	event.remove({output: 'cataclysm:monstrous_eye'})
	event.remove({output: 'cataclysm:abyss_eye'})
	event.remove({output: 'cataclysm:void_eye'})

	// Remove Golden Apples craft recipe
	event.remove({output: 'minecraft:golden_apple'})

	// Remove Experience Obelisk items recipes
	event.remove({output: 'experienceobelisk:xpobelisk'})

	// Remove Target Dummy recipe
	event.remove({output: 'dummmmmmy:dummy_crafting'})

	// Remove Skinned Lanterns recipes
	event.remove({output: 'skinnedlanterns:pufferfish_lantern_block'})
	event.remove({output: 'skinnedlanterns:zombie_lantern_block'})
	event.remove({output: 'skinnedlanterns:creeper_lantern_block'})
	event.remove({output: 'skinnedlanterns:skeleton_lantern_block'})
	event.remove({output: 'skinnedlanterns:wither_skeleton_lantern_block'})
	event.remove({output: 'skinnedlanterns:bee_lantern_block'})
	event.remove({output: 'skinnedlanterns:jack_o_lantern_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_white_lantern_block'})
	event.remove({output: 'skinnedlanterns:ghost_lantern_block'})
	event.remove({output: 'skinnedlanterns:blinky_lantern_block'})
	event.remove({output: 'skinnedlanterns:pinky_lantern_block'})
	event.remove({output: 'skinnedlanterns:inky_lantern_block'})
	event.remove({output: 'skinnedlanterns:clyde_lantern_block'})
	event.remove({output: 'skinnedlanterns:pacman_lantern_block'})
	event.remove({output: 'skinnedlanterns:guardian_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_yellow_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_orange_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_blue_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_light_blue_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_cyan_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_lime_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_green_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_pink_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_brown_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_black_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_gray_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_light_gray_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_magenta_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_purple_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_red_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_blue_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_purple_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_lime_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_magenta_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_yellow_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_green_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_light_blue_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_cyan_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_pink_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_orange_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_brown_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_black_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_white_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_gray_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_light_gray_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_green_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_red_lantern_block'})
	event.remove({output: 'skinnedlanterns:snowman_lantern_block'})
	event.remove({output: 'skinnedlanterns:honey_lantern_block'})
	event.remove({output: 'skinnedlanterns:slime_lantern_block'})
	event.remove({output: 'skinnedlanterns:pufferfish_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:zombie_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:creeper_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:skeleton_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:wither_skeleton_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:bee_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:jack_o_lantern_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_white_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ghost_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:blinky_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:pinky_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:inky_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:clyde_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:pacman_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:guardian_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_yellow_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_orange_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_blue_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_light_blue_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_cyan_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_lime_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_green_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_pink_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_brown_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_black_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_gray_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_light_gray_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_magenta_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:paper_purple_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_red_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_blue_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_purple_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_lime_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_magenta_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_yellow_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_green_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_light_blue_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_cyan_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_pink_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_orange_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_brown_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_black_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_white_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_gray_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_light_gray_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_green_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:ornament_red_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:snowman_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:honey_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:slime_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:present_green_lantern_block'})
	event.remove({output: 'skinnedlanterns:present_green_soul_lantern_block'})
	event.remove({output: 'skinnedlanterns:present_red_lantern_block'})
	event.remove({output: 'skinnedlanterns:present_red_soul_lantern_block'})

	// Remove Paraglider recipes
	event.remove({output: 'vc_gliders:paraglider_wood'})
	event.remove({output: 'vc_gliders:paraglider_iron'})
	event.remove({output: 'vc_gliders:paraglider_gold'})
	event.remove({output: 'vc_gliders:paraglider_diamond'})
	event.remove({output: 'vc_gliders:paraglider_netherite'})
	event.remove({output: 'vc_gliders:copper_upgrade'})
	event.remove({output: 'vc_gliders:nether_upgrade'})
	event.remove({output: 'vc_gliders:reinforced_paper'})
	event.remove({output: 'vc_gliders:reinforced_paper_iron'})
	event.remove({output: 'vc_gliders:reinforced_paper_gold'})
	event.remove({output: 'vc_gliders:reinforced_paper_diamond'})
	event.remove({output: 'vc_gliders:reinforced_paper_netherite'})
	
	// Remove Supplementaries recipes
	event.remove({output: 'supplementaries:bamboo_spikes'})
	event.remove({output: 'supplementaries:slingshot'})

	// Remove Waystones recipes
	event.remove({output: 'waystones:waystone'})
	event.remove({output: 'waystones:mossy_waystone'})
	event.remove({output: 'waystones:sandy_waystone'})
	event.remove({output: 'waystones:sharestone'})
	event.remove({output: 'waystones:warp_plate'})
	event.remove({output: 'waystones:portstone'})
	event.remove({output: 'waystones:white_sharestone'})
	event.remove({output: 'waystones:orange_sharestone'})
	event.remove({output: 'waystones:magenta_sharestone'})
	event.remove({output: 'waystones:light_blue_sharestone'})
	event.remove({output: 'waystones:yellow_sharestone'})
	event.remove({output: 'waystones:lime_sharestone'})
	event.remove({output: 'waystones:pink_sharestone'})
	event.remove({output: 'waystones:gray_sharestone'})
	event.remove({output: 'waystones:light_gray_sharestone'})
	event.remove({output: 'waystones:cyan_sharestone'})
	event.remove({output: 'waystones:purple_sharestone'})
	event.remove({output: 'waystones:blue_sharestone'})
	event.remove({output: 'waystones:brown_sharestone'})
	event.remove({output: 'waystones:green_sharestone'})
	event.remove({output: 'waystones:red_sharestone'})
	event.remove({output: 'waystones:black_sharestone'})
	event.remove({output: 'waystones:return_scroll'})
	event.remove({output: 'waystones:bound_scroll'})
	event.remove({output: 'waystones:warp_scroll'})
	event.remove({output: 'waystones:warp_stone'})
	event.remove({output: 'waystones:warp_dust'})
	event.remove({output: 'waystones:attuned_shard'})

	// Remove Meet Your Fight recipes
	event.remove({output: 'meetyourfight:haunted_bell'})
	event.remove({output: 'meetyourfight:passages_toll'})
	event.remove({output: 'meetyourfight:devils_ante'})
	event.remove({output: 'meetyourfight:fossil_bait'})
	event.remove({output: 'meetyourfight:dusk_key'})
	event.remove({output: 'meetyourfight:haunted_bell'})

	// Remove Straw Statue recipes
	event.remove({output: 'strawstatues:straw_statue'})

	// Remove Banned Blocks GUI recipes
	event.remove({output: 'minecraft:anvil'})
	event.remove({output: 'minecraft:chipped_anvil'})
	event.remove({output: 'minecraft:damaged_anvil'})
	event.remove({output: 'minecraft:enchanting_table'})
	event.remove({output: 'minecraft:brewing_stand'})
	event.remove({output: 'minecraft:smithing_table'})
	event.remove({output: 'cataclysm:mechanical_fusion_anvil'})
	event.remove({output: 'cataclysm:abyssal_sacrifice'})

	// Remove Monsters & Mushrooms recipes
	event.remove({output: 'monstersandmushrooms:bugsy_helmet'})
	event.remove({output: 'monstersandmushrooms:bugsy_chestplate'})
	event.remove({output: 'monstersandmushrooms:bugsy_leggings'})
	event.remove({output: 'monstersandmushrooms:bugsy_boots'})

	event.remove({output: 'monstersandmushrooms:shroomster_helmet'})
	event.remove({output: 'monstersandmushrooms:shroomster_chestplate'})
	event.remove({output: 'monstersandmushrooms:shroomster_leggings'})
	event.remove({output: 'monstersandmushrooms:shroomster_boots'})

	event.remove({output: 'monstersandmushrooms:maggart_helmet'})
	event.remove({output: 'monstersandmushrooms:maggart_chestplate'})
	event.remove({output: 'monstersandmushrooms:maggart_leggings'})
	event.remove({output: 'monstersandmushrooms:maggart_boots'})

	event.remove({output: 'monstersandmushrooms:bugsywand'})
	event.remove({output: 'monstersandmushrooms:shroomsterstaff'})
	event.remove({output: 'monstersandmushrooms:maggartstaff'})

	event.remove({output: 'monstersandmushrooms:rocky_moss'})
	event.remove({output: 'monstersandmushrooms:calcite_bricks'})
	event.remove({output: 'monstersandmushrooms:cobbled_coal'})
	event.remove({output: 'monstersandmushrooms:icy_deepslate_tiles'})
	event.remove({output: 'monstersandmushrooms:polished_amethyst'})

	// Remove Alexsmobs recipes
	event.remove({output: 'alexsmobs:transmutation_table'})
	event.remove({output: 'alexsmobs:tarantula_hawk_elytra'})
	event.remove({output: 'alexsmobs:tarantula_hawk_wing'})
	event.remove({output: 'alexsmobs:tattered_tarantula_hawk_wing'})
	event.remove({output: 'alexsmobs:endolocator'})

	// Remove Upgrade Aquatic unoobtainable item recipes
	event.remove({output: 'upgrade_aquatic:tongue_kelp'})
	event.remove({output: 'upgrade_aquatic:tongue_kelp_block'})
	event.remove({output: 'upgrade_aquatic:thorny_kelp_block'})
	event.remove({output: 'upgrade_aquatic:ochre_kelp_block'})
	event.remove({output: 'upgrade_aquatic:polar_kelp_block'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_cobblestone'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_cobblestone_stairs'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_cobblestone_slab'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_cobblestone_vertical_slab'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_stone_bricks'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_stone_brick_stairs'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_stone_brick_slab'})
	event.remove({output: 'upgrade_aquatic:tongue_kelpy_stone_brick_vertical_slab'})
	event.remove({output: 'upgrade_aquatic:thorny_kelp'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_cobblestone'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_cobblestone_stairs'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_cobblestone_slab'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_cobblestone_vertical_slab'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_stone_bricks'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_stone_brick_stairs'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_stone_brick_slab'})
	event.remove({output: 'upgrade_aquatic:thorny_kelpy_stone_brick_vertical_slab'})
	event.remove({output: 'upgrade_aquatic:polar_kelp'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_cobblestone'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_cobblestone_stairs'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_cobblestone_slab'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_cobblestone_vertical_slab'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_stone_bricks'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_stone_brick_stairs'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_stone_brick_slab'})
	event.remove({output: 'upgrade_aquatic:polar_kelpy_stone_brick_vertical_slab'})
	event.remove({output: 'upgrade_aquatic:ochre_kelp'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_cobblestone'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_cobblestone_stairs'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_cobblestone_slab'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_cobblestone_vertical_slab'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_stone_bricks'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_stone_brick_stairs'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_stone_brick_slab'})
	event.remove({output: 'upgrade_aquatic:ochre_kelpy_stone_brick_vertical_slab'})
	
	// Remove Create item recipes
	event.remove({output: 'create:schematicannon'})
	event.remove({output: 'create:schematic_table'})
	event.remove({output: 'create:shaft'})
	event.remove({output: 'create:cogwheel'})
	event.remove({output: 'create:large_cogwheel'})
	event.remove({output: 'create:gearbox'})
	event.remove({output: 'create:vertical_gearbox'})
	event.remove({output: 'create:clutch'})
	event.remove({output: 'create:gearshift'})
	event.remove({output: 'create:encased_chain_drive'})
	event.remove({output: 'create:adjustable_chain_gearshift'})
	event.remove({output: 'create:creative_motor'})
	event.remove({output: 'create:water_wheel'})
	event.remove({output: 'create:large_water_wheel'})
	event.remove({output: 'create:encased_fan'})
	event.remove({output: 'create:nozzle'})
	event.remove({output: 'create:turntable'})
	event.remove({output: 'create:hand_crank'})
	event.remove({output: 'create:cuckoo_clock'})
	event.remove({output: 'create:millstone'})
	event.remove({output: 'create:crushing_wheel'})
	event.remove({output: 'create:mechanical_press'})
	event.remove({output: 'create:mechanical_mixer'})
	event.remove({output: 'create:basin'})
	event.remove({output: 'create:empty_blaze_burner'})
	event.remove({output: 'create:blaze_burner'})
	event.remove({output: 'create:depot'})
	event.remove({output: 'create:weighted_ejector'})
	event.remove({output: 'create:chute'})
	event.remove({output: 'create:smart_chute'})
	event.remove({output: 'create:speedometer'})
	event.remove({output: 'create:stressometer'})
	event.remove({output: 'create:wooden_bracket'})
	event.remove({output: 'create:metal_bracket'})
	event.remove({output: 'create:fluid_pipe'})
	event.remove({output: 'create:mechanical_pump'})
	event.remove({output: 'create:smart_fluid_pipe'})
	event.remove({output: 'create:fluid_valve'})
	event.remove({output: 'create:copper_valve_handle'})
	event.remove({output: 'create:white_valve_handle'})
	event.remove({output: 'create:orange_valve_handle'})
	event.remove({output: 'create:magenta_valve_handle'})
	event.remove({output: 'create:light_blue_valve_handle'})
	event.remove({output: 'create:yellow_valve_handle'})
	event.remove({output: 'create:lime_valve_handle'})
	event.remove({output: 'create:pink_valve_handle'})
	event.remove({output: 'create:gray_valve_handle'})
	event.remove({output: 'create:light_gray_valve_handle'})
	event.remove({output: 'create:cyan_valve_handle'})
	event.remove({output: 'create:purple_valve_handle'})
	event.remove({output: 'create:blue_valve_handle'})
	event.remove({output: 'create:brown_valve_handle'})
	event.remove({output: 'create:green_valve_handle'})
	event.remove({output: 'create:red_valve_handle'})
	event.remove({output: 'create:black_valve_handle'})
	event.remove({output: 'create:fluid_tank'})
	event.remove({output: 'create:creative_fluid_tank'})
	event.remove({output: 'create:hose_pulley'})
	event.remove({output: 'create:item_drain'})
	event.remove({output: 'create:spout'})
	event.remove({output: 'create:portable_fluid_interface'})
	event.remove({output: 'create:steam_engine'})
	event.remove({output: 'create:steam_whistle'})
	event.remove({output: 'create:mechanical_piston'})
	event.remove({output: 'create:sticky_mechanical_piston'})
	event.remove({output: 'create:piston_extension_pole'})
	event.remove({output: 'create:gantry_carriage'})
	event.remove({output: 'create:gantry_shaft'})
	event.remove({output: 'create:windmill_bearing'})
	event.remove({output: 'create:mechanical_bearing'})
	event.remove({output: 'create:clockwork_bearing'})
	event.remove({output: 'create:rope_pulley'})
	event.remove({output: 'create:elevator_pulley'})
	event.remove({output: 'create:cart_assembler'})
	event.remove({output: 'create:controller_rail'})
	event.remove({output: 'create:linear_chassis'})
	event.remove({output: 'create:secondary_linear_chassis'})
	event.remove({output: 'create:radial_chassis'})
	event.remove({output: 'create:sticker'})
	event.remove({output: 'create:contraption_controls'})
	event.remove({output: 'create:mechanical_drill'})
	event.remove({output: 'create:mechanical_saw'})
	event.remove({output: 'create:deployer'})
	event.remove({output: 'create:portable_storage_interface'})
	event.remove({output: 'create:redstone_contact'})
	event.remove({output: 'create:mechanical_harvester'})
	event.remove({output: 'create:mechanical_plough'})
	event.remove({output: 'create:mechanical_roller'})
	event.remove({output: 'create:sail_frame'})
	event.remove({output: 'create:white_sail'})
	event.remove({output: 'create:andesite_casing'})
	event.remove({output: 'create:brass_casing'})
	event.remove({output: 'create:copper_casing'})
	event.remove({output: 'create:mechanical_crafter'})
	event.remove({output: 'create:sequenced_gearshift'})
	event.remove({output: 'create:flywheel'})
	event.remove({output: 'create:rotation_speed_controller'})
	event.remove({output: 'create:mechanical_arm'})
	event.remove({output: 'create:track'})
	event.remove({output: 'create:railway_casing'})
	event.remove({output: 'create:schedule'})
	event.remove({output: 'create:track_station'})
	event.remove({output: 'create:track_signal'})
	event.remove({output: 'create:track_observer'})
	event.remove({output: 'create:controls'})
	event.remove({output: 'create:item_vault'})
	event.remove({output: 'create:andesite_funnel'})
	event.remove({output: 'create:brass_funnel'})
	event.remove({output: 'create:andesite_tunnel'})
	event.remove({output: 'create:brass_tunnel'})
	event.remove({output: 'create:content_observer'})
	event.remove({output: 'create:stockpile_switch'})
	event.remove({output: 'create:creative_crate'})
	event.remove({output: 'create:display_link'})
	event.remove({output: 'create:display_board'})
	event.remove({output: 'create:nixie_tube'})
	event.remove({output: 'create:rose_quartz_lamp'})
	event.remove({output: 'create:redstone_link'})
	event.remove({output: 'create:analog_lever'})
	event.remove({output: 'create:placard'})
	event.remove({output: 'create:pulse_repeater'})
	event.remove({output: 'create:pulse_extender'})
	event.remove({output: 'create:powered_latch'})
	event.remove({output: 'create:powered_toggle_latch'})
	event.remove({output: 'create:cinder_flour'})
	event.remove({output: 'create:rose_quartz'})
	event.remove({output: 'create:polished_rose_quartz'})
	event.remove({output: 'create:powdered_obsidian'})
	event.remove({output: 'create:sturdy_sheet'})
	event.remove({output: 'create:propeller'})
	event.remove({output: 'create:whisk'})
	event.remove({output: 'create:brass_hand'})
	event.remove({output: 'create:crafter_slot_cover'})
	event.remove({output: 'create:electron_tube'})
	event.remove({output: 'create:precision_mechanism'})
	event.remove({output: 'create:blaze_cake_base'})
	event.remove({output: 'create:blaze_cake'})
	event.remove({output: 'create:creative_blaze_cake'})
	event.remove({output: 'create:bar_of_chocolate'})
	event.remove({output: 'create:sweet_roll'})
	event.remove({output: 'create:chocolate_glazed_berries'})
	event.remove({output: 'create:raw_zinc'})
	event.remove({output: 'create:andesite_alloy'})
	event.remove({output: 'create:zinc_ingot'})
	event.remove({output: 'create:brass_ingot'})
	event.remove({output: 'create:copper_nugget'})
	event.remove({output: 'create:zinc_nugget'})
	event.remove({output: 'create:brass_nugget'})
	event.remove({output: 'create:copper_sheet'})
	event.remove({output: 'create:schematicannon'})
	event.remove({output: 'create:brass_sheet'})
	event.remove({output: 'create:iron_sheet'})
	event.remove({output: 'create:golden_sheet'})
	event.remove({output: 'create:crushed_raw_zinc'})
	event.remove({output: 'create:belt_connector'})
	event.remove({output: 'create:goggles'})
	event.remove({output: 'create:super_glue'})
	event.remove({output: 'create:minecart_coupling'})
	event.remove({output: 'create:crafting_blueprint'})
	event.remove({output: 'create:copper_backtank'})
	event.remove({output: 'create:netherite_backtank'})
	event.remove({output: 'create:sand_paper'})
	event.remove({output: 'create:red_sand_paper'})
	event.remove({output: 'create:wrench'})
	event.remove({output: 'create:linked_controller'})
	event.remove({output: 'create:potato_cannon'})
	event.remove({output: 'create:extendo_grip'})
	event.remove({output: 'create:wand_of_symmetry'})
	event.remove({output: 'create:handheld_worldshaper'})
	event.remove({output: 'create:filter'})
	event.remove({output: 'create:attribute_filter'})
	event.remove({output: 'create:empty_schematic'})
	event.remove({output: 'create:schematic_and_quill'})
	event.remove({output: 'create:clipboard'})
	event.remove({output: 'create:andesite_ladder'})
	event.remove({output: 'create:brass_ladder'})
	event.remove({output: 'create:andesite_bars'})
	event.remove({output: 'create:brass_bars'})
	event.remove({output: 'create:andesite_scaffolding'})
	event.remove({output: 'create:brass_scaffolding'})
	event.remove({output: 'create:metal_girder'})
	event.remove({output: 'create:copycat_step'})
	event.remove({output: 'create:copycat_panel'})
	event.remove({output: 'create:schematicannon'})
	event.remove({output: 'create:andesite_door'})
	event.remove({output: 'create:brass_door'})
	event.remove({output: 'create:copper_door'})
	event.remove({output: 'create:train_door'})
	event.remove({output: 'create:train_trapdoor'})
	event.remove({output: 'create:zinc_ore'})
	event.remove({output: 'create:deepslate_zinc_ore'})
	event.remove({output: 'create:raw_zinc_block'})
	event.remove({output: 'create:zinc_block'})
	event.remove({output: 'create:andesite_alloy_block'})
	event.remove({output: 'create:industrial_iron_block'})
	event.remove({output: 'create:brass_block'})
	event.remove({output: 'create:experience_block'})
	event.remove({output: 'create:rose_quartz_block'})
	event.remove({output: 'create:rose_quartz_tiles'})
	event.remove({output: 'create:small_rose_quartz_tiles'})
	event.remove({output: 'create:honey_bucket'})
	event.remove({output: 'create:chocolate_bucket'})
	

// ====================================================================================================================
// =============================================== Create Craft Recipes ===============================================
// ====================================================================================================================

    // Witch Eye
	event.recipes.summoningrituals.altar("minecraft:ender_pearl")
	.input(Ingredient.of('endrem:witch_pupil', 1))
	.itemOutput('1x endrem:witch_eye')

	//Exotic Eye
	event.recipes.summoningrituals.altar("minecraft:ender_pearl")
	.input(Ingredient.of('minecraft:bubble_coral', 1))
	.input(Ingredient.of('minecraft:fire_coral', 1))
	.input(Ingredient.of('minecraft:horn_coral', 1))
	.input(Ingredient.of('minecraft:tube_coral', 1))
	.input(Ingredient.of('minecraft:conduit', 2))
	.input(Ingredient.of('minecraft:glow_ink_sac', 2))
	.itemOutput('1x endrem:exotic_eye')

	//Undead Eye
	event.recipes.summoningrituals.altar("endrem:undead_soul")
	.input(Ingredient.of('minecraft:bone', 1))
	.input(Ingredient.of('minecraft:phantom_membrane', 1))
	.input(Ingredient.of('minecraft:rotten_flesh', 1))
	.input(Ingredient.of('minecraft:ghast_tear', 1))
	.itemOutput('1x endrem:undead_eye')

	// Bottle o' Enchanting
	event.recipes.summoningrituals.altar("minecraft:glass_bottle")
	.input(Ingredient.of('minecraft:lapis_lazuli', 6))
	.input(Ingredient.of('minecraft:emerald', 3))
	.itemOutput('3x minecraft:experience_bottle')
	.recipeTime(25)

	// Enchanted Golden Apple
	event.recipes.summoningrituals.altar("minecraft:apple")
	.input(Ingredient.of('minecraft:gold_ingot', 8))
	.itemOutput('1x minecraft:golden_apple')
	.recipeTime(25)

	// Enchanted Golden Apple
	event.recipes.summoningrituals.altar("minecraft:apple")
	.input(Ingredient.of('minecraft:experience_bottle', 24))
	.input(Ingredient.of('minecraft:gold_block', 8))
	.itemOutput('1x minecraft:enchanted_golden_apple')
	.recipeTime(25)

	// Iron Apple
	event.recipes.summoningrituals.altar("minecraft:apple")
	.input(Ingredient.of('minecraft:iron_ingot', 8))
	.itemOutput('1x minecraft:iron_apple')
	.recipeTime(25)

	// Enchanted Iron Apple
	event.recipes.summoningrituals.altar("minecraft:apple")
	.input(Ingredient.of('minecraft:experience_bottle', 12))
	.input(Ingredient.of('minecraft:iron_block', 8))
	.itemOutput('1x minecraft:enchanted_iron_apple')
	.recipeTime(25)

	// Transform Magma Creams into Slimeballs
	event.recipes.summoningrituals.altar("minecraft:magma_cream")
	.itemOutput('1x minecraft:slime_ball')
	.recipeTime(25)

	// Transform Warped Ender Pearls into Ender Pearls
	event.recipes.summoningrituals.altar("bygonenether:warped_ender_pearl")
	.itemOutput('1x minecraft:ender_pearl')
	.recipeTime(25)

	// Fossil Bait
	event.recipes.summoningrituals.altar("minecraft:tropical_fish")
	.input(Ingredient.of('minecraft:rotten_flesh', 4))
	.input(Ingredient.of('minecraft:bone', 2))
	.input(Ingredient.of('minecraft:spider_eye', 2))
	.itemOutput('1x altar_of_summoning:fossilbait')

	// Haunted Bell
	event.recipes.summoningrituals.altar("minecraft:bell")
	.input(Ingredient.of('minecraft:soul_sand', 8))
	.itemOutput('1x altar_of_summoning:hauntedbell')

	// Devil's Ante
	event.recipes.summoningrituals.altar("alexsmobs:blood_sac")
	.input(Ingredient.of('minecraft:quartz', 8))
	.itemOutput('1x altar_of_summoning:devilsante')

	// Dusk Key
	event.recipes.summoningrituals.altar("mimic:mimic_key")
	.input(Ingredient.of('minecraft:amethyst_shard', 2))
	.input(Ingredient.of('minecraft:blackstone', 2))
	.input(Ingredient.of('minecraft:allium', 1))
	.itemOutput('1x altar_of_summoning:duskkey')

	// Abyssal Sacrifice
	event.recipes.summoningrituals.altar("minecraft:heart_of_the_sea")
	.input(Ingredient.of('cataclysm:athame', 1))
	.input(Ingredient.of('minecraft:nautilus_shell', 1))
	.input(Ingredient.of('cataclysm:crystallized_coral', 1))
	.input(Ingredient.of('minecraft:diamond_block', 1))
	.input(Ingredient.of('minecraft:iron_block', 1))
	.input(Ingredient.of('minecraft:emerald_block', 1))
	.input(Ingredient.of('minecraft:gold_block', 1))
	.input(Ingredient.of('minecraft:amethyst_block', 1))
	.itemOutput('1x cataclysm:abyssal_sacrifice')

	// Extract Materials from Vanilla Weapons & Armors

	// Leather
	event.recipes.summoningrituals.altar("minecraft:leather_helmet")
	.itemOutput('1x minecraft:leather')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:leather_chestplate")
	.itemOutput('1x minecraft:leather')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:leather_leggings")
	.itemOutput('1x minecraft:leather')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:leather_boots")
	.itemOutput('1x minecraft:leather')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:leather_horse_armor")
	.itemOutput('1x minecraft:leather')
	.recipeTime(25)

	// Chainmail
	event.recipes.summoningrituals.altar("minecraft:chainmail_helmet")
	.itemOutput('1x minecraft:iron_nugget')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:chainmail_chestplate")
	.itemOutput('1x minecraft:iron_nugget')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:chainmail_leggings")
	.itemOutput('1x minecraft:iron_nugget')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:chainmail_boots")
	.itemOutput('1x minecraft:iron_nugget')
	.recipeTime(25)

	// Iron
	event.recipes.summoningrituals.altar("minecraft:iron_helmet")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_chestplate")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_leggings")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_boots")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_sword")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_shovel")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_pickaxe")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_axe")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_hoe")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:iron_horse_armor")
	.itemOutput('1x minecraft:iron_ingot')
	.recipeTime(25)

	// Golden
	event.recipes.summoningrituals.altar("minecraft:golden_helmet")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_chestplate")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_leggings")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_boots")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_sword")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_shovel")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_pickaxe")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_axe")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_hoe")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:golden_horse_armor")
	.itemOutput('1x minecraft:gold_ingot')
	.recipeTime(25)

	// Diamond
	event.recipes.summoningrituals.altar("minecraft:diamond_helmet")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_chestplate")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_leggings")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_boots")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_sword")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_shovel")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_pickaxe")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_axe")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_hoe")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

	event.recipes.summoningrituals.altar("minecraft:diamond_horse_armor")
	.itemOutput('1x minecraft:diamond')
	.recipeTime(25)

// ====================================================================================================================
// ====================================================================================================================
// ====================================================================================================================
});