
[general]
	"Max Distance" = 24
	"Render with Interface Disabled (F1)" = false
	"Height Above Mob" = 0.3
	"Draw Background" = true
	"Background Padding" = 2
	"Background Height" = 6
	"Health Bar Height" = 4
	"Plate Size" = 25
	"Plate Size (Boss)" = 50
	"Show Attributes" = true
	"Show Armor" = true
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Color Health Bar by Type (instead of health percentage)" = false
	"HP Text Height" = 14
	"Show Max HP" = false
	"Show Current HP" = false
	"Show HP Percentage" = true
	"Display on Players" = false
	"Display on Bosses" = false
	"Only show the health bar for the entity looked at" = false
	"Show entities with full health" = true
	"Show Debug Info with F3" = false
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "alexsmobs:warped_mosco", "alexsmobs:void_worm", "alexsmobs:void_worm_part", "meetyourfight:dame_fortuna", "meetyourfight:bellringer", "meetyourfight:swampjaw", "minecraft:elder_guardian", "minecraft:wither", "cataclysm:ignis", "cataclysm:leviathan", "cataclysm:netherite_monstrosity", "cataclysm:ender_golem", "cataclysm:ender_guardian", "cataclysm:the_harbinger", "minecraft:warden", "meetyourfight:rosalyne", "meetyourfight:rose_spirit", "mutantmore:mutant_blaze", "mutantmore:mutant_shulker", "mutantmore:mutant_wither_skeleton", "alexsmobs:bone_serpent_part", "alexsmobs:centipede_body", "alexsmobs:murmur_head", "alexsmobs:centipede_tail", "minecraft:villager", "guardvillagers:guard", "mimic:mimic", "cataclysm:the_leviathan", "alexsmobs:anaconda_part", "dummmmmmy:target_dummy", "bte_mobs:blacksmith", "cataclysm:maledictus", "mutantmore:mutant_frozen_zombie", "mutantmore:mutant_hoglin", "mutantmore:mutant_husk", "mutantmore:mutant_jungle_zombie", "cataclysm:netherite_ministrosity"]

